name = "pizza-no-forninho"
compatibility_date = "2026-09-04"

[assets]
directory = "./"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "pizza-ni-forninho-db"
database_id = "730c99c0-f213-4790-8469-ea4219a66665"

# Opcional, para upload de fotos no futuro:
# [[r2_buckets]]
# binding = "MEDIA"
# bucket_name = "pizza-no-forninho-media"
